import React from 'react';
import { AlertCircle, ShieldAlert } from 'lucide-react';

interface ScientificDisclaimerProps {
  variant?: 'banner' | 'footer' | 'compact';
  className?: string;
  theme?: 'dark' | 'bright';
}

export const ScientificDisclaimer: React.FC<ScientificDisclaimerProps> = ({
  variant = 'banner',
  className = '',
  theme = 'dark',
}) => {
  const isDark = theme === 'dark';

  if (variant === 'compact') {
    return (
      <div
        id="scientific-disclaimer-compact"
        className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[11px] font-medium border ${
          isDark
            ? 'bg-amber-500/10 border-amber-500/20 text-amber-300'
            : 'bg-amber-50 border-amber-300 text-amber-900'
        } ${className}`}
      >
        <AlertCircle className="w-3.5 h-3.5 shrink-0 text-amber-500" />
        <span>Research Prototype: Model predictions are computational approximations.</span>
      </div>
    );
  }

  if (variant === 'footer') {
    return (
      <footer
        id="scientific-disclaimer-footer"
        className={`w-full py-4 border-t text-center text-xs px-4 mt-auto transition-colors ${
          isDark
            ? 'border-slate-800/80 bg-slate-950/80 text-slate-400'
            : 'border-slate-200 bg-white/90 text-slate-600'
        } ${className}`}
      >
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center gap-2 text-left">
            <ShieldAlert className="w-4 h-4 text-amber-500 shrink-0" />
            <p className="text-[11px] leading-relaxed">
              <strong className={isDark ? 'text-slate-200' : 'text-slate-800'}>Research Prototype:</strong> Predictions are computational estimates and are not a substitute for laboratory validation, clinical testing, or regulatory approval.
            </p>
          </div>
          <div className="text-[11px] shrink-0 font-mono-code text-teal-500">
            MolQuantum Engine v2.4
          </div>
        </div>
      </footer>
    );
  }

  return (
    <div
      id="scientific-disclaimer-banner"
      className={`w-full border-y px-4 py-1.5 text-xs flex items-center justify-center gap-2 backdrop-blur-md transition-colors ${
        isDark
          ? 'bg-gradient-to-r from-amber-500/10 via-slate-900/60 to-teal-500/10 border-amber-500/20 text-slate-300'
          : 'bg-gradient-to-r from-amber-500/15 via-amber-50/80 to-teal-500/15 border-amber-200 text-amber-950 shadow-xs'
      } ${className}`}
    >
      <AlertCircle className="w-4 h-4 text-amber-500 shrink-0" />
      <span className="leading-snug">
        <strong className={isDark ? 'text-amber-300 font-medium' : 'text-amber-900 font-bold'}>Research Prototype</strong> &mdash; Computational predictions are not experimentally validated and should not be interpreted as clinical conclusions.
      </span>
    </div>
  );
};

export const ScientificFooter: React.FC<{ 
  onNavigate?: (page: any) => void; 
  className?: string;
  theme?: 'dark' | 'bright';
  appName?: string;
}> = ({
  onNavigate,
  className = '',
  theme = 'dark',
  appName = 'MolQuantum AI',
}) => {
  const isDark = theme === 'dark';

  return (
    <footer
      id="scientific-platform-footer"
      className={`w-full border-t text-xs px-4 py-6 mt-auto transition-colors duration-200 ${
        isDark 
          ? 'border-slate-800/80 bg-slate-950/90 text-slate-400' 
          : 'border-slate-200 bg-white/90 text-slate-600 shadow-inner'
      } ${className}`}
    >
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-3 text-left">
          <ShieldAlert className="w-5 h-5 text-amber-500 shrink-0" />
          <p className="text-[11px] leading-relaxed max-w-2xl">
            <strong className={isDark ? 'text-amber-300 font-semibold' : 'text-amber-900 font-bold'}>Scientific Notice:</strong> Research Prototype &mdash; Computational predictions generated by {appName} are in-silico approximations and do not constitute medical, clinical, or diagnostic advice.
          </p>
        </div>

        <div className="flex items-center gap-4 text-xs">
          {onNavigate && (
            <>
              <button
                type="button"
                onClick={() => onNavigate('research')}
                className={`transition cursor-pointer ${isDark ? 'text-slate-400 hover:text-teal-300' : 'text-slate-600 hover:text-teal-700 font-medium'}`}
              >
                Methodology
              </button>
              <button
                type="button"
                onClick={() => onNavigate('quantum')}
                className={`transition cursor-pointer ${isDark ? 'text-slate-400 hover:text-violet-300' : 'text-slate-600 hover:text-violet-700 font-medium'}`}
              >
                Quantum Roadmap
              </button>
              <button
                type="button"
                onClick={() => onNavigate('settings')}
                className={`transition cursor-pointer ${isDark ? 'text-slate-400 hover:text-sky-300' : 'text-slate-600 hover:text-sky-700 font-medium'}`}
              >
                Settings
              </button>
            </>
          )}
          <span className="text-[11px] text-teal-500 font-mono-code font-medium">
            {appName} v2.4
          </span>
        </div>
      </div>
    </footer>
  );
};
